apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-deployment
  labels:
    app: keycloak
spec:
  replicas: 3
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - name: keycloak
        image: docker.io/keycloak/keycloak:26.5
        ports:
        - containerPort: 8080
        env:
          - name: KC_DB
            value: postgres
          - name: KC_DB_URL_HOST
            value: postgres.default.svc.cluster.local
          - name: KC_DB_URL_PORT
            value: "5432"
          - name: KC_DB_URL_DATABASE
            value: keycloak_db
          - name: KC_DB_USERNAME
            value: user
          - name: KC_DB_PASSWORD
            value: user
          - name: KC_BOOTSTRAP_ADMIN_USERNAME
            value: admin
          - name: KC_BOOTSTRAP_ADMIN_PASSWORD
            value: admin
        command:
          - "/opt/keycloak/bin/kc.sh"
          - "start-dev"